// Code generated by go-bindata.
// sources:
// assets/Makefile
// assets/formula.rb
// DO NOT EDIT!

package command

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _assetsMakefile = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x4c\x8e\x31\x4f\xc3\x30\x10\x85\x67\xfc\x2b\x4e\x2a\x43\x3b\xc4\x01\x06\x86\x48\x99\x00\x89\x02\x4d\x11\x14\x24\x46\x13\x5f\x62\x8b\x24\xb6\xec\x73\x0b\xb2\xfa\xdf\x49\x42\x68\xbb\xf8\xfc\x9e\xee\x7b\xef\x66\x6c\x06\x2b\xf1\x85\x95\x6e\x90\x0d\xe2\xc6\xd8\x1f\xa7\x6b\x45\x30\x2f\x17\x70\x75\x71\x79\x0d\x0f\xa1\xb3\xa8\xe1\x51\xec\x44\x6b\xc8\x8c\x6b\x1b\xa5\x3d\x78\x53\xd1\x4e\x38\x84\xfe\xef\xb0\x41\xe1\x51\x42\xe8\x24\x3a\x20\x85\xb0\x5a\x6e\xe0\x49\x97\xd8\x79\xe4\x23\xa4\x88\x6c\x96\xa6\xc6\xf6\x96\x09\xae\x44\x6e\x5c\x9d\x36\x7f\x2b\x3e\x6d\x35\x25\x93\xe0\x56\xd9\x1e\x79\xbf\x7b\x79\x5d\xae\x0b\xc8\xc1\x77\xc2\x7a\x65\x88\x31\x89\x95\x08\x0d\x65\xf0\x19\x74\x23\x19\xe3\xcf\xf7\xeb\xe2\xe3\x5f\x8e\x6f\xc6\xce\x6a\xf3\x5d\x42\x22\xf3\x18\xf9\x2d\x7a\xda\xef\x21\xb1\xdb\xfc\x7c\x3e\x25\x2e\x8e\xdc\x74\x38\x9b\xe6\xc0\x2a\x07\x31\xea\x0a\xf8\x9b\x47\x57\x88\x16\x07\x3c\xf4\xde\xa9\x11\x23\x76\xb2\x9f\xdb\x63\x28\x1c\xda\xd2\x93\xa6\xdf\x00\x00\x00\xff\xff\xc3\xc8\x51\x50\x63\x01\x00\x00")

func assetsMakefileBytes() ([]byte, error) {
	return bindataRead(
		_assetsMakefile,
		"assets/Makefile",
	)
}

func assetsMakefile() (*asset, error) {
	bytes, err := assetsMakefileBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/Makefile", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _assetsFormulaRb = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xbc\x51\x4f\x0b\xd3\x30\x14\xbf\xf7\x53\x3c\xba\x8b\x1e\x4c\x74\xce\x22\x43\xf0\x30\x18\xf3\x2f\x3b\x6c\x5e\x47\xda\xbc\x36\xc1\x34\x29\x79\xe9\xc6\xa8\xfd\xee\x26\x6d\xc5\x89\x28\x78\x11\x4a\xc9\x7b\xbf\xbf\x6d\x56\xd9\x0a\x04\x11\x06\xe2\xb5\xf3\x6d\x6f\x04\xf3\x65\x96\xb6\x3b\xd7\xdd\xbd\x6e\x54\x80\x27\xd5\x53\x58\x3f\x7f\x51\xc0\xfb\xde\x76\xa8\xe1\x83\xb8\x89\xd6\x05\x37\xd1\x4e\x4a\x13\x90\xab\xc3\x4d\x78\x84\x78\xf6\x68\x50\x10\x4a\xe8\xad\x44\x0f\x41\x21\x7c\x7a\x77\x82\x8f\xba\x42\x4b\xc8\x26\x91\x0a\xa1\xdb\x72\xee\xba\xb8\x72\xbd\xaf\x90\x39\xdf\x70\x33\x53\x88\xb7\x3a\x3c\x5b\x06\xd6\xa9\x2e\x4a\x2a\x13\x4b\xc2\x30\xb0\xa3\xa8\xbe\x8a\x06\xe1\x1b\x9c\x74\x30\x38\x8e\xf0\x06\xf6\x73\xf1\x0c\x40\x22\x55\x90\xe7\xf1\xa4\x5c\x8b\x5d\x22\xe6\x29\x8b\x62\x58\xa3\x83\xea\x4b\x56\xb9\x96\x47\x9f\x33\xa1\xff\x2c\xda\x68\xc0\x7f\xba\x8e\x63\x92\x5e\xd1\x93\x76\x16\xf2\x61\x88\x0f\xfb\x32\x8f\x11\x4b\x70\xc4\x75\x0d\x07\xe1\x65\xfa\xde\xed\x76\x77\x3c\x33\x4d\x97\x62\x73\x29\x75\x78\x1b\x51\x80\xde\x9b\x7f\x4c\xe5\xcb\x3f\x23\x2e\xdd\xcd\x1a\x27\x24\xbf\xfe\x1e\xce\xe7\xd5\x5e\x1b\x4c\x1e\xc5\x66\xa9\x94\x32\x49\x89\xf5\xab\xe2\x47\xe5\x83\x20\xf5\x00\xa3\x21\xfc\x9f\xcd\x5e\xbe\x2e\xfe\x5a\xed\x11\x47\x2b\xb3\xe9\xe2\x6a\xd0\x96\x82\x30\x66\x12\x95\xda\xb2\x65\x4e\xca\x5f\x2f\x68\xd1\x04\xa4\x00\xd2\xcd\x21\x77\x0a\xd8\xfe\x81\x9a\x5e\xdf\x03\x00\x00\xff\xff\x49\x9c\xf1\x21\xe8\x02\x00\x00")

func assetsFormulaRbBytes() ([]byte, error) {
	return bindataRead(
		_assetsFormulaRb,
		"assets/formula.rb",
	)
}

func assetsFormulaRb() (*asset, error) {
	bytes, err := assetsFormulaRbBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "assets/formula.rb", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"assets/Makefile": assetsMakefile,
	"assets/formula.rb": assetsFormulaRb,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"assets": &bintree{nil, map[string]*bintree{
		"Makefile": &bintree{assetsMakefile, map[string]*bintree{}},
		"formula.rb": &bintree{assetsFormulaRb, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

